// Real data from EO Arizona — FY 2026-2027 (Aug–May)
// President's Theme: "Every Day"
// Sub-themes: UNIVERSE, CHANGE, DISCIPLINE, RELATIONSHIPS
// FY ends June 30. Last learning event: May (Gratitude Gala).

const uuid = () => crypto.randomUUID()

export const mockChapter = {
  id: uuid(),
  name: 'EO Arizona',
  fiscal_year_start: 8,
  total_budget: 450000,
  president_theme: 'Every Day',
  president_name: '',
}

// ── VENUES ──────────────────────────────────────────────

export const mockVenues = [
  {
    id: 'venue-ballroom',
    chapter_id: mockChapter.id,
    name: 'Any Ballroom (TBD)',
    address: 'Scottsdale/Phoenix, AZ',
    capacity: 200,
    base_rental_cost: 5000,
    av_quality: 'good',
    av_cost_estimate: 3500,
    venue_type: 'hotel',
    notes: 'Generic ballroom placeholder. Good for traditional learning events with blindfold experience.',
    contact_name: '',
    contact_email: '',
  },
  {
    id: 'venue-heard',
    chapter_id: mockChapter.id,
    name: 'Heard Museum',
    address: 'Phoenix, AZ',
    capacity: 150,
    base_rental_cost: 4000,
    av_quality: 'good',
    av_cost_estimate: 3000,
    venue_type: 'other',
    notes: 'Cultural venue. Great setting for empathy/kindness themes.',
    contact_name: '',
    contact_email: '',
  },
  {
    id: 'venue-spring-training',
    chapter_id: mockChapter.id,
    name: 'Spring Training Field - Scottsdale',
    address: 'Scottsdale, AZ',
    capacity: 100,
    base_rental_cost: 3000,
    av_quality: 'fair',
    av_cost_estimate: 5000,
    venue_type: 'other',
    notes: 'Experiential venue for Jim Abbott. Outdoor — need strong AV.',
    contact_name: '',
    contact_email: '',
  },
  {
    id: 'venue-dbt',
    chapter_id: mockChapter.id,
    name: 'Ullman Terrace at Desert Botanical Garden',
    address: 'Phoenix, AZ',
    capacity: 120,
    base_rental_cost: 6000,
    av_quality: 'good',
    av_cost_estimate: 4000,
    venue_type: 'other',
    notes: 'Stunning outdoor terrace. Perfect for Priya Parker and the Art of Gathering theme.',
    contact_name: '',
    contact_email: '',
  },
  {
    id: 'venue-next-level',
    chapter_id: mockChapter.id,
    name: 'Next Level',
    address: 'Scottsdale, AZ',
    capacity: 64,
    base_rental_cost: 3000,
    av_quality: 'good',
    av_cost_estimate: 2000,
    venue_type: 'restaurant',
    notes: 'Jeffersonian Dinner venue. 8 tables of 8.',
    contact_name: '',
    contact_email: '',
  },
  {
    id: 'venue-dorrance',
    chapter_id: mockChapter.id,
    name: 'The Dorrance DOME',
    address: 'Phoenix, AZ',
    capacity: 200,
    base_rental_cost: 5000,
    av_quality: 'excellent',
    av_cost_estimate: 3000,
    venue_type: 'other',
    notes: 'January double-header venue. Dr. Paul Davies + Wesley Huff.',
    contact_name: '',
    contact_email: '',
  },
  {
    id: 'venue-wrigley',
    chapter_id: mockChapter.id,
    name: 'The Wrigley Mansion',
    address: 'Phoenix, AZ',
    capacity: 100,
    base_rental_cost: 7000,
    av_quality: 'good',
    av_cost_estimate: 3500,
    venue_type: 'other',
    notes: 'Iconic venue. Perfect for Dr. Gary Chapman / 5 Love Languages / Rose Ceremony.',
    contact_name: '',
    contact_email: '',
  },
  {
    id: 'venue-civic-center',
    chapter_id: mockChapter.id,
    name: 'Scottsdale Civic Center Park',
    address: 'Scottsdale, AZ',
    capacity: 200,
    base_rental_cost: 2000,
    av_quality: 'fair',
    av_cost_estimate: 6000,
    venue_type: 'other',
    notes: 'Outdoor park. Cesar Millan "bring your dog" event. Need strong outdoor AV.',
    contact_name: '',
    contact_email: '',
  },
  {
    id: 'venue-music',
    chapter_id: mockChapter.id,
    name: 'Music Museum / Phoenix Symphony',
    address: 'Phoenix, AZ',
    capacity: 150,
    base_rental_cost: 5000,
    av_quality: 'excellent',
    av_cost_estimate: 2000,
    venue_type: 'other',
    notes: 'Indre Viskontas lecture-performance venue. Built-in acoustics.',
    contact_name: '',
    contact_email: '',
  },
]

// ── SPEAKERS ────────────────────────────────────────────

export const mockSpeakers = [
  // ─── BOOKED / IN PROGRESS ───
  {
    id: 'spk-salim',
    chapter_id: mockChapter.id,
    name: 'Salim Ismail',
    topic: 'Exponential Organizations — AI, Disruption & the Future',
    bio: 'Author of "Exponential Organizations." Former Executive Director of Singularity University. Leading voice on how AI and exponential technologies are transforming business and society.',
    fee_range_low: 30000,
    fee_range_high: 50000,
    contact_email: '',
    contact_phone: '',
    agency_name: '',
    agency_contact: '',
    contact_method: 'direct',
    pipeline_stage: 'outreach',
    fit_score: 10,
    notes: 'KICKOFF SPEAKER. AI-themed kickoff for the "Every Day" theme — every day the world is changing exponentially. Salim shows us how to ride the wave instead of being swept away.',
    routing_flexibility: false,
    multi_chapter_interest: true,
  },
  {
    id: 'spk-erik',
    chapter_id: mockChapter.id,
    name: 'Erik Weihenmayer',
    topic: 'Overcoming the Impossible — First Blind Everest Summiteer',
    bio: 'First blind person to reach the summit of Mount Everest (May 25, 2001). Climbed all Seven Summits. Motivational speaker and author.',
    fee_range_low: 30000,
    fee_range_high: 50000,
    contact_email: '',
    contact_phone: '',
    agency_name: 'Chartwell Speakers',
    agency_contact: '',
    contact_method: 'agency',
    pipeline_stage: 'passed',
    fit_score: 9,
    notes: 'Originally planned for August kickoff. Replaced with Salim Ismail (AI-themed kickoff). Blindfold experience concept shelved. Could be revisited for a future month.',
    routing_flexibility: false,
    multi_chapter_interest: false,
  },
  {
    id: 'spk-brad',
    chapter_id: mockChapter.id,
    name: 'Brad Montague',
    topic: 'Joyful Rebellion — Kindness, Empathy & Playfulness',
    bio: 'Creator known for emphasizing kindness, empathy, and maintaining a sense of playfulness. Advocates for "joyful rebellion" — challenging negativity with positivity.',
    fee_range_low: 10000,
    fee_range_high: 20000,
    contact_email: '',
    contact_phone: '',
    agency_name: '',
    agency_contact: '',
    contact_method: 'direct',
    pipeline_stage: 'outreach',
    fit_score: 8,
    notes: 'Submitted booking request via montagueworkshop.com/contact. Great CHANGE theme fit. Embracing our inner child leads to a more compassionate world.',
    routing_flexibility: true,
    multi_chapter_interest: false,
  },
  {
    id: 'spk-jim',
    chapter_id: mockChapter.id,
    name: 'Jim Abbott',
    topic: 'Discipline & Overcoming — Born Without a Right Hand, Pitched for the Yankees',
    bio: 'Overcame being born without a right hand to pitch for the New York Yankees, including throwing a no-hitter.',
    fee_range_low: 15000,
    fee_range_high: 40000,
    contact_email: '',
    contact_phone: '',
    agency_name: 'AAE Speakers Bureau',
    agency_contact: '',
    contact_method: 'agency',
    pipeline_stage: 'outreach',
    fit_score: 9,
    notes: 'Sent booking request to AAE. DISCIPLINE theme. Spring Training Field venue — experiential setting.',
    routing_flexibility: false,
    multi_chapter_interest: false,
  },
  {
    id: 'spk-priya',
    chapter_id: mockChapter.id,
    name: 'Priya Parker',
    topic: 'The Art of Gathering — Connection, Purpose & Belonging',
    bio: 'Author of The Art of Gathering. Teaches how to design gatherings that create connection, purpose, and belonging. Excellent for leaders who want practical tools to deepen relationships at scale.',
    fee_range_low: 25000,
    fee_range_high: 40000,
    contact_email: '',
    contact_phone: '',
    agency_name: 'Celebrity Talent',
    agency_contact: 'celebritytalent.net',
    contact_method: 'agency',
    pipeline_stage: 'outreach',
    fit_score: 10,
    notes: 'Submitted request via Celebrity Talent. RELATIONSHIPS theme. We all know what makes EO relationships special — Priya gives us tools to bring that je ne sais quoi to ALL our relationships. Speaking sample: youtube.com/watch?v=ppfONdsOkWI',
    routing_flexibility: false,
    multi_chapter_interest: false,
  },
  {
    id: 'spk-davies',
    chapter_id: mockChapter.id,
    name: 'Dr. Paul Davies',
    topic: 'The Universe, Physics & the Big Questions',
    bio: 'Theoretical physicist, cosmologist, and astrobiologist. ASU professor. Deep thinker on the origin of life and the nature of the universe.',
    fee_range_low: 10000,
    fee_range_high: 20000,
    contact_email: '',
    contact_phone: '',
    agency_name: '',
    agency_contact: '',
    contact_method: 'direct',
    pipeline_stage: 'outreach',
    fit_score: 8,
    notes: 'UNIVERSE theme. January double-header with Wesley Huff at The Dorrance DOME. Email and phone requests sent.',
    routing_flexibility: false,
    multi_chapter_interest: false,
  },
  {
    id: 'spk-wesley',
    chapter_id: mockChapter.id,
    name: 'Wesley Huff',
    topic: 'Faith, Reason & the Universe',
    bio: 'Speaker on faith and reason. Paired with Dr. Paul Davies for a compelling dialogue on the universe.',
    fee_range_low: 5000,
    fee_range_high: 20000,
    contact_email: '',
    contact_phone: '',
    agency_name: '',
    agency_contact: '',
    contact_method: 'direct',
    pipeline_stage: 'outreach',
    fit_score: 7,
    notes: 'UNIVERSE theme. January double-header with Dr. Paul Davies at The Dorrance DOME. Email and phone requests sent.',
    routing_flexibility: false,
    multi_chapter_interest: false,
  },
  {
    id: 'spk-chapman',
    chapter_id: mockChapter.id,
    name: 'Dr. Gary Chapman',
    topic: 'The 5 Love Languages — Relationships That Thrive Every Day',
    bio: 'Author of "The 5 Love Languages: How to Express Heartfelt Commitment to Your Mate." One of the most influential relationship authors alive.',
    fee_range_low: 10000,
    fee_range_high: 20000,
    contact_email: '',
    contact_phone: '',
    agency_name: '',
    agency_contact: '5lovelanguages.com',
    contact_method: 'direct',
    pipeline_stage: 'outreach',
    fit_score: 9,
    notes: 'Submitted booking request. RELATIONSHIPS theme. SAP Tie-In: Culture Index. Unexpected: Jesse Palmer from The Bachelor. Interactivity: Rose Ceremony + Culture Index Analysis (high level). Marriage can be a challenge — if you treat EVERY DAY like a gift, you can make meaningful progress.',
    routing_flexibility: false,
    multi_chapter_interest: false,
  },
  {
    id: 'spk-cesar',
    chapter_id: mockChapter.id,
    name: 'Cesar Millan',
    topic: 'Discipline, Energy & the Dog Whisperer Approach to Leadership',
    bio: 'World-famous dog behaviorist. Known as the Dog Whisperer. Teaches how discipline, calm energy, and intentional approach transforms relationships.',
    fee_range_low: 50000,
    fee_range_high: 100000,
    contact_email: '',
    contact_phone: '1.800.698.2536',
    agency_name: '',
    agency_contact: '',
    contact_method: 'direct',
    pipeline_stage: 'outreach',
    fit_score: 10,
    notes: 'Submitted booking request. Phone: 1.800.698.2536. DISCIPLINE theme. How you approach others matters — if you have the discipline to do it right, magical things can happen. Dogs naturally treat EVERY DAY as a gift. Unexpected: Bring your dog! Cesar may engage your pet during the event.',
    routing_flexibility: false,
    multi_chapter_interest: false,
  },
  {
    id: 'spk-indre',
    chapter_id: mockChapter.id,
    name: 'Indre Viskontas',
    topic: 'Music, Neuroscience & the Universe of Sound',
    bio: 'Soprano with a PhD in neuroscience who gives lecture-performances on how music reshapes attention and emotion.',
    fee_range_low: null,
    fee_range_high: null,
    contact_email: '',
    contact_phone: '',
    agency_name: '',
    agency_contact: '',
    contact_method: 'direct',
    pipeline_stage: 'outreach',
    fit_score: 8,
    notes: 'Left message via website. UNIVERSE theme. The universe of Music — how it can help you reset your mind, adjust your attitude, and frame your emotional state. Speaking sample: youtube.com/watch?v=AJYRJ92g4GI',
    routing_flexibility: false,
    multi_chapter_interest: false,
  },

  // ─── RESEARCHING (no dates yet) ───
  {
    id: 'spk-tour',
    chapter_id: mockChapter.id,
    name: 'Dr. James Tour',
    topic: 'Organic Chemistry & the Origin of Life',
    bio: 'Organic chemist and creationist. Provocative thinker on the origin of life.',
    fee_range_low: null,
    fee_range_high: null,
    contact_email: '',
    contact_phone: '',
    agency_name: '',
    agency_contact: '',
    contact_method: 'direct',
    pipeline_stage: 'researching',
    fit_score: 7,
    notes: 'UNIVERSE theme. Alternate speaker option. Organic Chemist - Creationist.',
    routing_flexibility: false,
    multi_chapter_interest: false,
  },
  {
    id: 'spk-cox',
    chapter_id: mockChapter.id,
    name: 'Brian Cox',
    topic: 'The Wonders of the Universe',
    bio: 'Astronomer, physicist, and BBC presenter. One of the most popular science communicators in the world.',
    fee_range_low: null,
    fee_range_high: null,
    contact_email: '',
    contact_phone: '',
    agency_name: '',
    agency_contact: '',
    contact_method: 'agency',
    pipeline_stage: 'researching',
    fit_score: 8,
    notes: 'UNIVERSE theme. Alternate speaker option. Major name recognition.',
    routing_flexibility: false,
    multi_chapter_interest: false,
  },
  {
    id: 'spk-ingrid',
    chapter_id: mockChapter.id,
    name: 'Ingrid Fetell Lee',
    topic: 'Joyful — The Surprising Power of Ordinary Things',
    bio: 'Author of "Joyful: The Surprising Power of Ordinary Things to Create Extraordinary Happiness."',
    fee_range_low: null,
    fee_range_high: null,
    contact_email: '',
    contact_phone: '',
    agency_name: '',
    agency_contact: '',
    contact_method: 'direct',
    pipeline_stage: 'researching',
    fit_score: 7,
    notes: 'UNIVERSE theme. Alternate speaker option.',
    routing_flexibility: false,
    multi_chapter_interest: false,
  },
  {
    id: 'spk-wallace',
    chapter_id: mockChapter.id,
    name: 'Jennifer Wallace',
    topic: 'Why We Need to Know Our Lives Matter',
    bio: 'Author and speaker on mattering — why knowing our lives matter is essential to well-being.',
    fee_range_low: null,
    fee_range_high: null,
    contact_email: '',
    contact_phone: '',
    agency_name: '',
    agency_contact: '',
    contact_method: 'direct',
    pipeline_stage: 'researching',
    fit_score: 7,
    notes: 'UNIVERSE theme. Alternate speaker option. TED talk: ted.com/talks/jennifer_wallace_why_we_need_to_know_our_lives_matter',
    routing_flexibility: false,
    multi_chapter_interest: false,
  },
]

// ── EVENTS ──────────────────────────────────────────────

export const mockEvents = [
  {
    id: 'evt-aug',
    chapter_id: mockChapter.id,
    title: 'CHANGE: The Exponential Future',
    event_date: '2026-08-13',
    event_time: '18:00',
    month_index: 0,
    event_type: 'traditional',
    strategic_importance: 'kickoff',
    theme_connection: 'CHANGE — Every day the world is changing exponentially. Salim Ismail shows us how to harness AI and exponential tech to transform our businesses and lives.',
    status: 'planning',
    speaker_id: 'spk-salim',
    venue_id: 'venue-ballroom',
    day_chair_name: '',
    day_chair_phone: '',
    expected_attendance: 150,
    actual_attendance: null,
    nps_score: null,
    nps_top_takeaway: null,
    notes: 'KICKOFF EVENT. AI-themed kickoff with Salim Ismail. Set the tone for the "Every Day" year — the world changes every day, and exponential thinking is how we stay ahead.',
  },
  {
    id: 'evt-sep',
    chapter_id: mockChapter.id,
    title: 'CHANGE: Joyful Rebellion',
    event_date: '2026-09-24',
    event_time: '18:00',
    month_index: 1,
    event_type: 'traditional',
    strategic_importance: 'momentum',
    theme_connection: 'CHANGE — Every day is a chance to challenge negativity with positivity. Treat everyone with dignity and respect. Embrace your inner child.',
    status: 'planning',
    speaker_id: 'spk-brad',
    venue_id: 'venue-heard',
    day_chair_name: '',
    day_chair_phone: '',
    expected_attendance: 100,
    actual_attendance: null,
    nps_score: null,
    nps_top_takeaway: null,
    notes: 'Brad Montague at the Heard Museum.',
  },
  {
    id: 'evt-oct',
    chapter_id: mockChapter.id,
    title: 'DISCIPLINE: No Excuses',
    event_date: '2026-10-28',
    event_time: '18:00',
    month_index: 2,
    event_type: 'experiential',
    strategic_importance: 'momentum',
    theme_connection: 'DISCIPLINE — Born without a right hand, Jim Abbott pitched a no-hitter for the Yankees. Every day he chose discipline over excuse.',
    status: 'planning',
    speaker_id: 'spk-jim',
    venue_id: 'venue-spring-training',
    day_chair_name: '',
    day_chair_phone: '',
    expected_attendance: 100,
    actual_attendance: null,
    nps_score: null,
    nps_top_takeaway: null,
    notes: 'Jim Abbott at Spring Training Field. Experiential setting.',
  },
  {
    id: 'evt-nov',
    chapter_id: mockChapter.id,
    title: 'RELATIONSHIPS: The Art of Gathering',
    event_date: '2026-11-11',
    event_time: '18:00',
    month_index: 3,
    event_type: 'traditional',
    strategic_importance: 'momentum',
    theme_connection: 'RELATIONSHIPS — We all know what makes EO relationships special. Priya gives us tools to bring that je ne sais quoi to ALL our relationships.',
    status: 'planning',
    speaker_id: 'spk-priya',
    venue_id: 'venue-dbt',
    day_chair_name: '',
    day_chair_phone: '',
    expected_attendance: 120,
    actual_attendance: null,
    nps_score: null,
    nps_top_takeaway: null,
    notes: 'Priya Parker at Ullman Terrace, Desert Botanical Garden.',
  },
  {
    id: 'evt-dec',
    chapter_id: mockChapter.id,
    title: 'RELATIONSHIPS: Jeffersonian Dinner',
    event_date: '2026-12-10',
    event_time: '18:30',
    month_index: 4,
    event_type: 'key_relationships',
    strategic_importance: 'holiday',
    theme_connection: 'RELATIONSHIPS — 8 tables of 8, sorted first to produce Respect, and second, Joy. Deep connection over shared food.',
    status: 'planning',
    speaker_id: null,
    venue_id: 'venue-next-level',
    day_chair_name: '',
    day_chair_phone: '',
    expected_attendance: 64,
    actual_attendance: null,
    nps_score: null,
    nps_top_takeaway: null,
    notes: 'No speaker — this is a facilitated Jeffersonian Dinner. Groups sorted to produce Respect and Joy.',
  },
  {
    id: 'evt-jan',
    chapter_id: mockChapter.id,
    title: 'UNIVERSE: The Big Questions',
    event_date: '2027-01-19',
    event_time: '18:00',
    month_index: 5,
    event_type: 'traditional',
    strategic_importance: 'renewal_critical',
    theme_connection: 'UNIVERSE — Every day, the universe invites us to ask bigger questions. Two brilliant minds, one dome, infinite wonder.',
    status: 'planning',
    speaker_id: 'spk-davies',
    venue_id: 'venue-dorrance',
    day_chair_name: '',
    day_chair_phone: '',
    expected_attendance: 150,
    actual_attendance: null,
    nps_score: null,
    nps_top_takeaway: null,
    notes: 'RENEWAL MONTH — must be strong. Double-header: Dr. Paul Davies + Wesley Huff at The Dorrance DOME.',
  },
  {
    id: 'evt-feb',
    chapter_id: mockChapter.id,
    title: 'RELATIONSHIPS: The 5 Love Languages',
    event_date: '2027-02-02',
    event_time: '18:00',
    month_index: 6,
    event_type: 'traditional',
    strategic_importance: 'renewal_critical',
    theme_connection: 'RELATIONSHIPS — Marriage can be a challenge. But if you treat EVERY DAY like a gift, an opportunity to start fresh, you can make meaningful progress toward restoring and building one of the most important relationships in your life.',
    status: 'planning',
    speaker_id: 'spk-chapman',
    venue_id: 'venue-wrigley',
    day_chair_name: '',
    day_chair_phone: '',
    expected_attendance: 100,
    actual_attendance: null,
    nps_score: null,
    nps_top_takeaway: null,
    notes: 'RENEWAL MONTH — critical for retention. Dr. Gary Chapman at The Wrigley Mansion. SAP Tie-In: Culture Index. Unexpected: Jesse Palmer from The Bachelor. Interactivity: Rose Ceremony + Culture Index Analysis.',
  },
  {
    id: 'evt-mar',
    chapter_id: mockChapter.id,
    title: 'DISCIPLINE: The Dog Whisperer',
    event_date: '2027-03-17',
    event_time: '10:00',
    month_index: 7,
    event_type: 'experiential',
    strategic_importance: 'sustain',
    theme_connection: 'DISCIPLINE — How you approach others matters. If you have the discipline to do it right, magical things happen. Dogs naturally treat EVERY DAY as a gift.',
    status: 'planning',
    speaker_id: 'spk-cesar',
    venue_id: 'venue-civic-center',
    day_chair_name: '',
    day_chair_phone: '',
    expected_attendance: 120,
    actual_attendance: null,
    nps_score: null,
    nps_top_takeaway: null,
    notes: 'Cesar Millan at Scottsdale Civic Center Park. BRING YOUR DOG! Cesar may engage your pet during the event. Outdoor event — need strong AV.',
  },
  {
    id: 'evt-apr',
    chapter_id: mockChapter.id,
    title: 'UNIVERSE: Music & the Mind',
    event_date: '2027-04-27',
    event_time: '18:00',
    month_index: 8,
    event_type: 'experiential',
    strategic_importance: 'sustain',
    theme_connection: 'UNIVERSE — The universe of Music and how it can help you reset your mind, adjust your attitude, and frame your emotional state. You see God\'s work within its ordered beauty.',
    status: 'planning',
    speaker_id: 'spk-indre',
    venue_id: 'venue-music',
    day_chair_name: '',
    day_chair_phone: '',
    expected_attendance: 120,
    actual_attendance: null,
    nps_score: null,
    nps_top_takeaway: null,
    notes: 'Indre Viskontas lecture-performance at Music Museum or Phoenix Symphony.',
  },
  {
    id: 'evt-may',
    chapter_id: mockChapter.id,
    title: 'Gratitude Gala',
    event_date: '2027-05-20',
    event_time: '18:00',
    month_index: 9,
    event_type: 'social',
    strategic_importance: 'strong_close',
    theme_connection: 'Every Day is a gift — and tonight we celebrate a year of growth, connection, and gratitude. Thank you for making Every Day count.',
    status: 'planning',
    speaker_id: null,
    venue_id: null,
    day_chair_name: '',
    day_chair_phone: '',
    expected_attendance: 150,
    actual_attendance: null,
    nps_score: null,
    nps_top_takeaway: null,
    notes: 'FINAL EVENT of the FY. Gratitude Gala — celebrate the year, recognize day chairs, thank the president. Venue TBD.',
  },
]

// ── BUDGET ITEMS ────────────────────────────────────────

export const mockBudgetItems = [
  // August — Salim Ismail (AI Kickoff)
  { id: uuid(), event_id: 'evt-aug', category: 'speaker_fee', description: 'Salim Ismail keynote', estimated_amount: 40000, actual_amount: null },
  { id: uuid(), event_id: 'evt-aug', category: 'food_beverage', description: 'Kickoff dinner', estimated_amount: 15000, actual_amount: null },
  { id: uuid(), event_id: 'evt-aug', category: 'venue_rental', description: 'Ballroom rental', estimated_amount: 5000, actual_amount: null },
  { id: uuid(), event_id: 'evt-aug', category: 'av_production', description: 'AV + screens', estimated_amount: 5000, actual_amount: null },

  // September — Brad Montague
  { id: uuid(), event_id: 'evt-sep', category: 'speaker_fee', description: 'Brad Montague keynote', estimated_amount: 15000, actual_amount: null },
  { id: uuid(), event_id: 'evt-sep', category: 'food_beverage', description: 'Dinner', estimated_amount: 10000, actual_amount: null },
  { id: uuid(), event_id: 'evt-sep', category: 'venue_rental', description: 'Heard Museum', estimated_amount: 4000, actual_amount: null },
  { id: uuid(), event_id: 'evt-sep', category: 'av_production', description: 'AV', estimated_amount: 3000, actual_amount: null },

  // October — Jim Abbott
  { id: uuid(), event_id: 'evt-oct', category: 'speaker_fee', description: 'Jim Abbott keynote', estimated_amount: 25000, actual_amount: null },
  { id: uuid(), event_id: 'evt-oct', category: 'food_beverage', description: 'Catering at field', estimated_amount: 12000, actual_amount: null },
  { id: uuid(), event_id: 'evt-oct', category: 'venue_rental', description: 'Spring Training Field', estimated_amount: 3000, actual_amount: null },
  { id: uuid(), event_id: 'evt-oct', category: 'av_production', description: 'Outdoor AV setup', estimated_amount: 5000, actual_amount: null },

  // November — Priya Parker
  { id: uuid(), event_id: 'evt-nov', category: 'speaker_fee', description: 'Priya Parker keynote', estimated_amount: 32000, actual_amount: null },
  { id: uuid(), event_id: 'evt-nov', category: 'food_beverage', description: 'Dinner at DBG', estimated_amount: 12000, actual_amount: null },
  { id: uuid(), event_id: 'evt-nov', category: 'venue_rental', description: 'Ullman Terrace', estimated_amount: 6000, actual_amount: null },
  { id: uuid(), event_id: 'evt-nov', category: 'av_production', description: 'AV', estimated_amount: 4000, actual_amount: null },

  // December — Jeffersonian Dinner
  { id: uuid(), event_id: 'evt-dec', category: 'food_beverage', description: 'Jeffersonian dinner for 64', estimated_amount: 8000, actual_amount: null },
  { id: uuid(), event_id: 'evt-dec', category: 'venue_rental', description: 'Next Level', estimated_amount: 3000, actual_amount: null },

  // January — Dr. Paul Davies + Wesley Huff
  { id: uuid(), event_id: 'evt-jan', category: 'speaker_fee', description: 'Dr. Paul Davies', estimated_amount: 15000, actual_amount: null },
  { id: uuid(), event_id: 'evt-jan', category: 'speaker_fee', description: 'Wesley Huff', estimated_amount: 10000, actual_amount: null },
  { id: uuid(), event_id: 'evt-jan', category: 'food_beverage', description: 'Dinner', estimated_amount: 12000, actual_amount: null },
  { id: uuid(), event_id: 'evt-jan', category: 'venue_rental', description: 'The Dorrance DOME', estimated_amount: 5000, actual_amount: null },
  { id: uuid(), event_id: 'evt-jan', category: 'av_production', description: 'AV', estimated_amount: 3000, actual_amount: null },

  // February — Dr. Gary Chapman
  { id: uuid(), event_id: 'evt-feb', category: 'speaker_fee', description: 'Dr. Gary Chapman keynote', estimated_amount: 15000, actual_amount: null },
  { id: uuid(), event_id: 'evt-feb', category: 'food_beverage', description: 'Rose Ceremony dinner', estimated_amount: 12000, actual_amount: null },
  { id: uuid(), event_id: 'evt-feb', category: 'venue_rental', description: 'The Wrigley Mansion', estimated_amount: 7000, actual_amount: null },
  { id: uuid(), event_id: 'evt-feb', category: 'av_production', description: 'AV', estimated_amount: 3500, actual_amount: null },

  // March — Cesar Millan
  { id: uuid(), event_id: 'evt-mar', category: 'speaker_fee', description: 'Cesar Millan appearance', estimated_amount: 65000, actual_amount: null },
  { id: uuid(), event_id: 'evt-mar', category: 'food_beverage', description: 'Outdoor catering (people + dogs)', estimated_amount: 10000, actual_amount: null },
  { id: uuid(), event_id: 'evt-mar', category: 'venue_rental', description: 'Civic Center Park', estimated_amount: 2000, actual_amount: null },
  { id: uuid(), event_id: 'evt-mar', category: 'av_production', description: 'Outdoor AV', estimated_amount: 6000, actual_amount: null },

  // April — Indre Viskontas
  { id: uuid(), event_id: 'evt-apr', category: 'speaker_fee', description: 'Indre Viskontas lecture-performance', estimated_amount: 15000, actual_amount: null },
  { id: uuid(), event_id: 'evt-apr', category: 'food_beverage', description: 'Dinner', estimated_amount: 10000, actual_amount: null },
  { id: uuid(), event_id: 'evt-apr', category: 'venue_rental', description: 'Music venue', estimated_amount: 5000, actual_amount: null },
  { id: uuid(), event_id: 'evt-apr', category: 'av_production', description: 'AV (venue has built-in)', estimated_amount: 2000, actual_amount: null },

  // May — Gratitude Gala
  { id: uuid(), event_id: 'evt-may', category: 'food_beverage', description: 'Gala dinner', estimated_amount: 20000, actual_amount: null },
  { id: uuid(), event_id: 'evt-may', category: 'venue_rental', description: 'Gala venue TBD', estimated_amount: 8000, actual_amount: null },
  { id: uuid(), event_id: 'evt-may', category: 'av_production', description: 'AV + lighting', estimated_amount: 5000, actual_amount: null },
  { id: uuid(), event_id: 'evt-may', category: 'other', description: 'Awards, recognition, decor', estimated_amount: 5000, actual_amount: null },
]

// ── CONTRACT CHECKLISTS ─────────────────────────────────

export const mockContractChecklists = [
  {
    id: uuid(),
    event_id: 'evt-aug',
    jurisdiction_local: false,
    indemnification_clause: false,
    mfn_clause: false,
    run_of_show_included: false,
    av_requirements_specified: false,
    cancellation_terms: false,
    recording_rights: false,
    contract_signed: false,
    contract_notes: 'Salim Ismail — awaiting response for August kickoff.',
  },
]
