// Mock data for development before Supabase is connected

const uuid = () => crypto.randomUUID()

export const mockChapter = {
  id: uuid(),
  name: 'EO Arizona',
  fiscal_year_start: 8,
  total_budget: 450000,
  president_theme: 'Every Day',
  president_name: '',
}

export const mockSpeakers = [
  {
    id: uuid(),
    chapter_id: mockChapter.id,
    name: 'Salim Ismail',
    topic: 'Exponential Organizations & AI Transformation',
    bio: 'Author of Exponential Organizations. Spoken at G20, TED, the Vatican, and the UN.',
    fee_range_low: 50000,
    fee_range_high: 100000,
    contact_email: '',
    contact_phone: '',
    agency_name: '',
    agency_contact: '',
    contact_method: 'agency',
    pipeline_stage: 'researching',
    fit_score: 9,
    notes: 'ExO is practically an EO bible. Audiences described as "blown away." Strong WOW factor for kickoff.',
    routing_flexibility: false,
    multi_chapter_interest: true,
  },
  {
    id: uuid(),
    chapter_id: mockChapter.id,
    name: 'Zack Kass',
    topic: 'AI, Abundance & the Future of Human Potential',
    bio: 'Former Head of Go-to-Market at OpenAI. Thought leader on AI abundance.',
    fee_range_low: 15000,
    fee_range_high: 25000,
    contact_email: '',
    contact_phone: '',
    agency_name: '',
    agency_contact: '',
    contact_method: 'direct',
    pipeline_stage: 'researching',
    fit_score: 8,
    notes: 'Lower recognition but perfect abundance fit. "You haven\'t heard of him yet" narrative. Budget-friendly.',
    routing_flexibility: true,
    multi_chapter_interest: false,
  },
  {
    id: uuid(),
    chapter_id: mockChapter.id,
    name: 'Allie K. Miller',
    topic: 'AI Strategy for Business Leaders',
    bio: 'Former Amazon AI lead. Forbes 30 Under 30. AI entrepreneur and advisor.',
    fee_range_low: 20000,
    fee_range_high: 30000,
    contact_email: '',
    contact_phone: '',
    agency_name: '',
    agency_contact: '',
    contact_method: 'linkedin',
    pipeline_stage: 'researching',
    fit_score: 7,
    notes: 'Moderate name recognition. Good AI fit. Strong EO fit.',
    routing_flexibility: true,
    multi_chapter_interest: false,
  },
  {
    id: uuid(),
    chapter_id: mockChapter.id,
    name: 'Paul Roetzer',
    topic: 'Marketing AI & Business Transformation',
    bio: 'Founder of Marketing AI Institute. Author of Marketing Artificial Intelligence.',
    fee_range_low: 15000,
    fee_range_high: 25000,
    contact_email: '',
    contact_phone: '',
    agency_name: '',
    agency_contact: '',
    contact_method: 'direct',
    pipeline_stage: 'outreach',
    fit_score: 7,
    notes: 'Practical AI applications for business owners. Good for traditional learning event.',
    routing_flexibility: true,
    multi_chapter_interest: false,
  },
]

export const mockVenues = [
  {
    id: uuid(),
    chapter_id: mockChapter.id,
    name: 'Scottsdale Resort at McCormick Ranch',
    address: '7700 E McCormick Pkwy, Scottsdale, AZ',
    capacity: 200,
    base_rental_cost: 5000,
    av_quality: 'good',
    av_cost_estimate: 3500,
    venue_type: 'hotel',
    notes: 'Reliable venue. Good for traditional learning events.',
    contact_name: '',
    contact_email: '',
  },
  {
    id: uuid(),
    chapter_id: mockChapter.id,
    name: 'Porsche Experience Center',
    address: 'Chandler, AZ',
    capacity: 80,
    base_rental_cost: 0,
    av_quality: 'excellent',
    av_cost_estimate: 2000,
    venue_type: 'dealership',
    notes: 'State-of-the-art AV. May waive venue fee for sponsorship access. Great for experiential events.',
    contact_name: '',
    contact_email: '',
  },
]

export const mockEvents = [
  {
    id: uuid(),
    chapter_id: mockChapter.id,
    title: 'Kickoff: AI & the Exponential Future',
    event_date: '2026-08-20',
    event_time: '18:00',
    month_index: 0,
    event_type: 'traditional',
    strategic_importance: 'kickoff',
    theme_connection: 'Every day we have the opportunity to leverage exponential technology to create abundance — for ourselves and our communities.',
    status: 'planning',
    speaker_id: null,
    venue_id: null,
    day_chair_name: '',
    day_chair_phone: '',
    expected_attendance: 120,
    actual_attendance: null,
    nps_score: null,
    nps_top_takeaway: null,
    notes: 'Marquee AI speaker. Set the tone for the year. Big energy.',
  },
  {
    id: uuid(),
    chapter_id: mockChapter.id,
    title: 'Leadership in the Arena',
    event_date: '2026-09-17',
    event_time: '18:00',
    month_index: 1,
    event_type: 'traditional',
    strategic_importance: 'momentum',
    theme_connection: 'Every day is a chance to step into the arena and lead.',
    status: 'planning',
    speaker_id: null,
    venue_id: null,
    day_chair_name: '',
    day_chair_phone: '',
    expected_attendance: 100,
    actual_attendance: null,
    nps_score: null,
    nps_top_takeaway: null,
    notes: '',
  },
  {
    id: uuid(),
    chapter_id: mockChapter.id,
    title: 'Navy SEAL Resilience Training',
    event_date: '2026-10-15',
    event_time: '08:00',
    month_index: 2,
    event_type: 'experiential',
    strategic_importance: 'momentum',
    theme_connection: 'Every day, SEALs choose to push beyond their limits. What would happen if we did the same?',
    status: 'planning',
    speaker_id: null,
    venue_id: null,
    day_chair_name: '',
    day_chair_phone: '',
    expected_attendance: 60,
    actual_attendance: null,
    nps_score: null,
    nps_top_takeaway: null,
    notes: 'Experiential OIL event. Full day.',
  },
]

export const mockBudgetItems = [
  { id: uuid(), event_id: mockEvents[0].id, category: 'speaker_fee', description: 'Keynote speaker', estimated_amount: 50000, actual_amount: null },
  { id: uuid(), event_id: mockEvents[0].id, category: 'food_beverage', description: 'Dinner service', estimated_amount: 12000, actual_amount: null },
  { id: uuid(), event_id: mockEvents[0].id, category: 'venue_rental', description: 'Venue rental', estimated_amount: 5000, actual_amount: null },
  { id: uuid(), event_id: mockEvents[0].id, category: 'av_production', description: 'Full AV package', estimated_amount: 5000, actual_amount: null },
  { id: uuid(), event_id: mockEvents[1].id, category: 'speaker_fee', description: 'Keynote speaker', estimated_amount: 25000, actual_amount: null },
  { id: uuid(), event_id: mockEvents[1].id, category: 'food_beverage', description: 'Dinner', estimated_amount: 10000, actual_amount: null },
  { id: uuid(), event_id: mockEvents[1].id, category: 'venue_rental', description: 'Venue', estimated_amount: 4000, actual_amount: null },
  { id: uuid(), event_id: mockEvents[1].id, category: 'av_production', description: 'AV', estimated_amount: 3500, actual_amount: null },
]

export const mockContractChecklists = [
  {
    id: uuid(),
    event_id: mockEvents[0].id,
    jurisdiction_local: false,
    indemnification_clause: false,
    mfn_clause: false,
    run_of_show_included: false,
    av_requirements_specified: false,
    cancellation_terms: false,
    recording_rights: false,
    contract_signed: false,
    contract_notes: '',
  },
]
