-- ============================================================
-- 073 Seed EO Global Speakers Academy speakers
-- ============================================================
-- Loads 92 speakers from the EO Global Speakers Academy
-- public database into public.public_speakers.
--
-- Source: https://event.eonetwork.org/global-speakers-academy/database/
-- Extracted to supabase/../eo_global_speakers_academy_database.xlsx
-- and converted to SQL for git tracking.
--
-- Idempotent via the (source, lower(name)) unique index from 072.
-- Re-running this migration does nothing for already-loaded rows;
-- a future migration can do an explicit UPDATE if GSA refreshes a entry.

insert into public.public_speakers (name, topic, eo_chapter, class_year, source, source_url) values
  ('ALEX RIVLIN', 'Kick Self-Doubt To The Curb', 'EO Las Vegas', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('AMIT KOTHARI', '3 Transformative Leadership Steps to Scale Your Business', 'EO Orange County', 'Spring 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('ANDREA HEUSTON', 'The Three Steps to Creating a Life of Opportunity and Grace through Gratitude', 'EO Interim', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('ANIMESH JAIN', 'The Family Business Continuity Mantra – Paving Way for a Lasting Legacy in Family Business for Future Generations', 'EO Bhopal', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('ANNA LECAT', 'Connective Cultures – master complexity, inspire unity, grow together', 'EO Zurich', 'Spring 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('ANTONY TINKER', 'Unstuck! Your Journey to Profit and Smiles', 'EO UK-London', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('ASHIF KASSAM', 'Introspection, Leadership Purpose, Self-discovery, Developing a Bequeathing Mindset, Personal Clarity, Your ah-ha Moment', 'EO Kenya', 'Fall 2024', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('ARI BROWN', 'Defining Success: This talk might save your life.', 'EO Austin', 'Spring 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('BRIAN BRAULT', 'Drivers of Success and Destruction: What Lies Beneath the Surface', 'EO Western New York', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('BROOKE LIVELY', '3 Key Strategies Fast-Growing Companies Use to Achieve More Profit', 'EO Fort Worth', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('CESAR QUINTERO', 'Unlock Your Flywheel to 10X Your Life', 'EO South Florida', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('CHRISTOPHER TARANTINO', 'Fireweed: Resilience & Innovation Grow Together', 'EO Colorado', 'Spring 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('DAVID ANDERSON', 'GLCx Incoming Global Chair Speech', 'EO Arizona', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('DAVE GALBENSKI', 'EO Confidential: I Sold My Business – Lessons Learned', 'EO Detroit', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('DAVID NILSSEN', 'Transforming Your Business With Global Talent', 'EO Seattle', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('DELANO MASSEY', '$200M+ in Less Than 5 Years: Learn How!', 'EO Atlanta', 'FALL 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('DHIREN HARCHANDANI', 'Master Your Inner Game', 'EO U.A.E.', 'Spring 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('DIVAKAR VIJAYASARATHY', 'Three Steps to Save Taxes Globally', 'EO New York', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('ERIN PHEIL', 'Getting Unstuck: The Elegant, Simple, and Wildly Effective Formula For (Finally) Optimizing What’s Not Optimal In Your Business + Personal Life', 'EO Colorado', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('ELIZABETH GARVISH', 'How I am creating the happiest law firm in America and how you can inject happiness into your workplace, life and beyond.', 'EO LAC Bridge', 'Spring 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('DR. ENRIQUE PRESBURGER', 'The Three Macroeconomic Mistakes: Understanding world financial trends', 'EO Mexico City', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('Frido van Mossel', 'Business and life shouldn’t be competing forces, but rather one integrated lifestyle experience where work, play, relationships, and growth blend together seamlessly.', 'EO Europe Bridge', 'Fall 2024', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('GAURAV JHUNJHNUWALA', 'Be Unstoppable – 3 Powerful lessons from the life of a blind entrepreneur', 'EO Gurgaon', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('HENRY ZIFF', 'Grow your business through acquisition and then SELL it to maximise its value', 'EO UK-London', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('HUGO DIAZ', 'Teams that Learn Together Stay Together', 'EO Austin', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('IAN EVENSTAR', 'Golden Triangle: A Secret System to Improve Profitability & Market Share', 'EO San Diego', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('JAIME MANN', 'Perfectionism / Imposter Syndrome / Taking out your mind trash', 'EO Winnipeg', 'Fall 2024', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('JASON BROWN', 'New to investing? Discover the Top 3 Secrets for Maximizing Profits and Reducing Risk in the Stock Market', 'EO Detroit', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('JAY WILKINSON', 'Mindsets of a Do More Good Leader', 'EO Nebraska', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('GIAN MARCO PALAZIO', 'Live Your Legacy: 3 Simple Actions for an Impactful Life', 'EO Nicaragua', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('JAHAN KALANTAR', 'Harness your Resilience – Learn to ride the storm', 'EO Sydney', 'Spring 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('JANE HALES', 'Curious Leadership: Strategies for driving growth mindset', 'EO UK-London', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('JENNY FETEROVICH', 'Tall Buildings, Sexy People, and Money Falling From The Sky: Why you need to abandon your fantasies to reach your dreams', 'EO Detroit', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('JESSICA FIALKOVICH', 'Why You Should Prepare Your Business For Sale Today, Not Tomorrow', 'EO Colorado', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('JESÚS DE LA GARZA', 'The 4 Functions of Teams', 'EO Monterrey', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('JOAQUIM ESTEVE', 'Mistakes in investing – Lessons for entrepreneurs', 'EO Barcelona', '2023', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('JODI COHEN', 'Activating Calm to Enhance Productivity', 'EO Idaho', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('JODI DANIELS', 'The One Way to Build Customer Trust You Should Never Skip', 'EO Atlanta', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('JONATHON HENSLEY', 'The Secret to Business Transformation and Achieving Extraordinary Results', 'EO Portland', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('JOSEPH FROST', 'The Future Is Fractional', 'EO Nebraska', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('JULIE HERZOG', 'What Doesn’t Kill You Makes You Stronger: How to Transform Your Stress Into Success', 'EO Colorado', 'Spring 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('JUAN FERNANDO GIRALDO', 'Unveil Your Narrative Power: Finding the Hero in Your Epic Story for Connection', 'EO Bogota', 'Fall 2023', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('LISA WISE', 'Stand up to Stand Out: the Justice Advantage in Business', 'EO DC', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('KARA BROWN', 'The 6 Figure LinkedIn Post: A 3-Step Formula for Repeatable Lead Generation', 'EO Atlanta', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('REV. K. BILL DOST', 'Raise Yourself from Debt to Wealth', 'EO Interim', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('KARL H. FUNKE', 'Elevate your game with clarity, focus, and mentor', 'EO Germany-Munich', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('KENT GREGOIRE', 'Navigating Chaos: The CEO’s Guide to Evolving Beyond Traditional Operating Systems', 'EO US Bridge', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('KIM WHITAKER', 'Uncertainty: The Greatest Gift', 'EO Cape Town', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('KRISTOPHER KLUVER', 'Life on Your Terms, Become the Leader that Achieves Unreasonable Success', 'Elumni', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('LAUREN REED', 'Taking the Five Percent from Forum to Real Life in Three Steps', 'EO Nashville', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('LOU ELLIOTT-CYSEWSKI', '3 Steps to Boost Profitability by Going Green', 'EO Seattle', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('MARC GUTMAN', '3 Mistakes Most Businesses are Making with their Brand', 'EO Colorado', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('MARC STÖCKLI', 'Three principles to create high-performing team', 'EO APAC Platinum One Bridge', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('MARIA LEVIS', 'Achieving Health, Impact and Joy in Business', 'EO Puerto Rico', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('MARINA BYEZHANOVA', 'Personal Branding Masterclass', 'EO Canada Bridge', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('DR. MARKUS WUEBBEN', 'Change is easy – with the power of positivity', 'EO Berlin', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('MARSHA RALLS', 'Rising From the Ashes – You Have the Power to Rewrite Your Story', 'EO LAC Bridge', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('MAXIM MULYADI', 'The three secrets great leaders do differently with their strengths to live their best possible life', 'EO Indonesia East', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('MICHAEL HSU', '3 secrets to enjoy life as an entrepreneur… without doing it all', 'EO Inland Empire', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('MICHAEL KORN', 'How to run your company without your company running you – Three ways to get more freedom and clarity by making sure everyone fits perfectly in their job', 'EO UK-London', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('MICHAEL SIMONSEN', 'Hacking Happiness', 'EO San Francisco', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('MICHAEL SCHOENBERGER', 'Connection, Heart Coherence, Leadership, Culture', 'EO Edmonton', 'Fall 2024', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('MICHEL KRIPALANI', 'Invest in your Relationships, Profit in your Life', 'EO San Diego', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('MICHÉLE HECKEN', 'The Art of Offboarding: Free your business to grow and create the the life of your dreams!', 'EO Canada Bridge', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('MIGUEL DE NARVAEZ', 'Fearless First. 3 Key Strategies to Rock your Entrepreneur Journey', 'EO Bogota', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('MORNÉ SMIT', '5 Unexpected Ways to Build a Winning Sales Culture', 'EO Elumni', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('NATALYA BERDIKYAN', 'Elevate your life, team and business', 'EO Spain-Barcelona', 'Spring 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('PAM HOWLAND', 'Law for Leaders: Keeping You Out Of The Courthouse', 'EO Idaho', 'Fall 2023', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('PATRICK BRYANT', '3 Secrets to Craft the Perfect Business', 'EO Charleston', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('PETER KELLER', 'Confident, Clear, Happy', 'EO Austin', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('RAMIRO SABORIO', 'Become Unstoppable: Accessing the Three Hidden Rules for Elite Entrepreneurs', 'EO Nicaragua', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('ROBERT HARTLINE', 'Scale your business in 24 Hours', 'EO Nashville', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('ROB STOLKER', 'Break Your Mould – Literally (How To Make Your Difference)', 'EO New Jersey', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('ROBYN ROSENBERGER', '3 Steps to Joy in all Circumstances', 'EO St. Louis', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('SAAHIL MEHTA', 'Scale your summits of success faster', 'EO U.A.E.', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('Sara Batalha', 'Leading with Influence: The Art and Science of Executive Communication', 'EO Portugal', 'Fall 2024', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('SCOTT EMPRINGHAM', 'Rising from the Ashes: A 90-Day Business Comeback Story Powered by Social Media and AI', 'EO Orange County', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('SCOTT NOVIS', 'Cheat Code – a parents’ guide to ending video game time without a fight, and how to manage video game safety', 'EO Arizona', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('SHIVANI GUPTA', 'Employee wellness', 'EO Queensland', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('SHREANS DAGA', 'Meditate Your Way To Success', 'EO Mumbai', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('SINAN GULER', 'Path of an Athlete: Connecting Sports Career & Lessons with Entrepreneurship and Building a Fulfilled Life.', 'EO Turkey', 'Fall 2024', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('STACY BAHRENFUSS', 'You get to have it all: 3 Secrets to freedom and fulfillment without compromising your business or financial success', 'EO Idaho', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('STEFFY ROOS DU MAINE', 'Secrets of a Mindful Millionaire: 3 spiritual insights for business success', 'EO Netherlands', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('STEPHANIE CAMARILLO', 'SHINE: How Empowered Employees Will Transform Your Workforce', 'EO Idaho', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('STEVE SCHAFFER', 'Chain Reactions: Increase your growth and profit with a metrics-driven strategy', 'EO Austin', 'Fall 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('SUE GRABOWSKI', 'How Process Can Power Your Service-Based Business', 'EO Cleveland', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('SUSAN DRUMM', 'The Leader’s Playlist: Unleash the Power of Music and Neuroscience to Transform Your Leadership and Your Life', 'EO Arizona', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('TEHSIN TAKIM', 'Beyond the Label: The Truth Behind Introvert Myths and Success', 'EO Tanzania', 'Spring 2022', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('TIM RETTIG', 'Exiting for Good: How I used employee ownership to scale and exit my company', 'EO Cincinnati', 'Fall 2024', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('Tracy Marlowe', 'Modern Marketing', 'EO Sacramento', 'Fall 2024', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('WINNIE HART', 'Stand Out as a Thought Leader', 'EO Houston', 'Spring 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/'),
  ('WILL SCOTT', 'The Gift of Culture', 'EO Wisconsin', 'Fall 2021', 'EO Global Speakers Academy', 'https://event.eonetwork.org/global-speakers-academy/database/')
on conflict (source, lower(name)) do nothing;

notify pgrst, 'reload schema';
